### ISSUE TITLE
[230926] Code Tree - 바이러스 백신

### ISSUE THREAD

**Issue by hadevyi** [SSAFY-Coach/SamsungAlgorithm-SecondHalf-23#13]
### 문제 개요

- 사이트 : CodeTree
- 제목 : 바이러스 백신
- 링크 : https://www.codetree.ai/training-field/frequent-problems/problems/vaccine-for-virus/description?page=1&pageSize=20&tier=1%2C12&statuses=Ready

**Comment by yoseph0310** [comment]
세상 뻘짓했네 이문제..
