### ISSUE TITLE
[230927] CodeTree - 토끼와 경주

### ISSUE THREAD

**Issue by DONG-8** [SSAFY-Coach/SamsungAlgorithm-SecondHalf-23#17]
### 문제 개요

- 사이트 : CodeTree
- 제목 : 토끼와 경주
- 링크 : https://www.codetree.ai/training-field/frequent-problems/problems/rabit-and-race/description?page=1&pageSize=20

**Comment by yoseph0310** [comment]
동우 코드 참고한것도 오답나서 일단 GG...

**Comment by yoseph0310** [comment]
하.. score를 long 하는 걸 잊어서 3일을 썼네.....
