### ISSUE TITLE
[230929] CodeTree - 포탑 부수기

### ISSUE THREAD

**Issue by pear96** [SSAFY-Coach/SamsungAlgorithm-SecondHalf-23#19]
### 문제 개요

- 사이트 : CodeTree
- 제목 : 포탑 부수기
- 링크 : https://www.codetree.ai/training-field/frequent-problems/problems/destroy-the-turret/description

**Comment by samsohn0128** [comment]
테케 6번 틀림
```
10 6 1000
3362 3908 4653 3746 4119 3669
4174 0 0 868 1062 854
633 51 759 0 4724 1474
2735 365 1750 3382 498 1672
141 3700 0 436 2752 974
3494 0 4719 2016 3870 0
3357 0 4652 3468 0 3758
4610 3125 0 2364 3303 1904
0 0 0 0 3959 3324
3187 0 105 2821 3642 160

정답: 727
출력: 649
```

도움....!!!

**Comment by yoseph0310** [comment]
> 테케 6번 틀림
> 
> ```
> 10 6 1000
> 3362 3908 4653 3746 4119 3669
> 4174 0 0 868 1062 854
> 633 51 759 0 4724 1474
> 2735 365 1750 3382 498 1672
> 141 3700 0 436 2752 974
> 3494 0 4719 2016 3870 0
> 3357 0 4652 3468 0 3758
> 4610 3125 0 2364 3303 1904
> 0 0 0 0 3959 3324
> 3187 0 105 2821 3642 160
> 
> 정답: 727
> 출력: 649
> ```
> 
> 도움....!!!

이문제부터 풀어봐야겠군 !

**Comment by yoseph0310** [comment]
> 테케 6번 틀림
> 
> ```
> 10 6 1000
> 3362 3908 4653 3746 4119 3669
> 4174 0 0 868 1062 854
> 633 51 759 0 4724 1474
> 2735 365 1750 3382 498 1672
> 141 3700 0 436 2752 974
> 3494 0 4719 2016 3870 0
> 3357 0 4652 3468 0 3758
> 4610 3125 0 2364 3303 1904
> 0 0 0 0 3959 3324
> 3187 0 105 2821 3642 160
> 
> 정답: 727
> 출력: 649
> ```
> 
> 도움....!!!

아.. 처음으로 이틀이나 걸렸네요 풀었슴다.... 푸셨슴까 동우좌?

**Comment by yoseph0310** [comment]
> 테케 6번 틀림
> 
> ```
> 10 6 1000
> 3362 3908 4653 3746 4119 3669
> 4174 0 0 868 1062 854
> 633 51 759 0 4724 1474
> 2735 365 1750 3382 498 1672
> 141 3700 0 436 2752 974
> 3494 0 4719 2016 3870 0
> 3357 0 4652 3468 0 3758
> 4610 3125 0 2364 3303 1904
> 0 0 0 0 3959 3324
> 3187 0 105 2821 3642 160
> 
> 정답: 727
> 출력: 649
> ```
> 
> 도움....!!!

그냥 일단 제 생각인데 레이저 루트 찾을 때 (167 라인부터) nodeStack으로 경로를 넣고 있는데
이게 'from -> to 로 가는 최단경로' 만이 아니라 BFS 탈때 'from -> to 로 방문해볼 수 있는 경우'들이 다 nodeStack에 들어가서 틀리는게 아닌가 조심스레 예상해봄다.. 

아니네 prevNode가 있네여 왜틀린거지 진짜

**Comment by samsohn0128** [comment]
> > 테케 6번 틀림
> > ```
> > 10 6 1000
> > 3362 3908 4653 3746 4119 3669
> > 4174 0 0 868 1062 854
> > 633 51 759 0 4724 1474
> > 2735 365 1750 3382 498 1672
> > 141 3700 0 436 2752 974
> > 3494 0 4719 2016 3870 0
> > 3357 0 4652 3468 0 3758
> > 4610 3125 0 2364 3303 1904
> > 0 0 0 0 3959 3324
> > 3187 0 105 2821 3642 160
> > 
> > 정답: 727
> > 출력: 649
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 도움....!!!
> 
> 그냥 일단 제 생각인데 레이저 루트 찾을 때 (167 라인부터) nodeStack으로 경로를 넣고 있는데 이게 'from -> to 로 가는 최단경로' 만이 아니라 BFS 탈때 'from -> to 로 방문해볼 수 있는 경우'들이 다 nodeStack에 들어가서 틀리는게 아닌가 조심스레 예상해봄다..
> 
> 아니네 prevNode가 있네여 왜틀린거지 진짜

ㅋㅋㅋㅋㄹㅇ 아무리 봐도 왜 틀렷는지 모루겟다

**Comment by samsohn0128** [comment]
요셉이거 보고 다시하는데 또 6번테케 이번엔 638나옴 ㅋㅋㅋ
뭐가 틀린거지...
```
10 6 1000
3362 3908 4653 3746 4119 3669
4174 0 0 868 1062 854
633 51 759 0 4724 1474
2735 365 1750 3382 498 1672
141 3700 0 436 2752 974
3494 0 4719 2016 3870 0
3357 0 4652 3468 0 3758
4610 3125 0 2364 3303 1904
0 0 0 0 3959 3324
3187 0 105 2821 3642 160

정답: 727
출력: 638
```

**Comment by yoseph0310** [comment]
ㅋㅋㅋㅋㅋㅋㅋ 서로 다른문제 참고하면서 난리부르스넼ㅋㅋㅋㅋㅋㅋㅋㅋㅋ
