### ISSUE TITLE
[230930] SW Expert Academy - 원자 소멸 시뮬레이션

### ISSUE THREAD

**Issue by yoseph0310** [SSAFY-Coach/SamsungAlgorithm-SecondHalf-23#21]
### 문제 개요

- 사이트 : SW Expert Academy
- 번호 : 5648
- 제목 : [모의 SW 역량테스트] 원자 소멸 시뮬레이션
- 링크 : https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRFInKex8DFAUo

**Comment by samsohn0128** [comment]
테케 49개 맞췄을 때는 뭐가 틀린지 알아서 고쳤는데
고쳤더니 47개 맞고 뭐가 틀린지 모르겟네요ㅋㅋㅋㅋ개빡세네

**Comment by yoseph0310** [comment]
> 테케 49개 맞췄을 때는 뭐가 틀린지 알아서 고쳤는데 고쳤더니 47개 맞고 뭐가 틀린지 모르겟네요ㅋㅋㅋㅋ개빡세네

동시에 3, 4개 만나는 것도 체킹이 되는건가..? Pair 로 짝지어놓고 터트리는 거라 잘 모르겠는데 그게 잘못되지 않았을까요

**Comment by samsohn0128** [comment]
> 동시에 3, 4개 만나는 것도 체킹이 되는건가..? Pair 로 짝지어놓고 터트리는 거라 잘 모르겠는데 그게 잘못되지 않았을까요

그래서 모든 Pair를 다 돌아보면서 하는건뎅...댓글에 있는거 동시에 3개 만나는것도 잘 됨 ㅠㅠ

**Comment by yoseph0310** [comment]
내일 리뷰때 다시 보는걸로.....!!
