### ISSUE TITLE
[231003] CodeTree - 격자 숫자 놀이

### ISSUE THREAD

**Issue by hadevyi** [SSAFY-Coach/SamsungAlgorithm-SecondHalf-23#24]
### 문제 개요

- 사이트 : CodeTree
- 제목 : 격자 숫자 놀이
- 출처 : 삼성SW역량테스트 2019 상반기 오후 1번
- 링크 : https://www.codetree.ai/training-field/frequent-problems/problems/matrix-number-play/description?page=2&pageSize=20

**Comment by samsohn0128** [comment]
디버깅 실력이 현저히 떨어지는 중...
테케 17번 틀림 흑흑
뭐가 틀린거지
```
9 30 12
94 90 37 
8 44 80 
40 1 91 

정답: 89
출력: -1
```

**Comment by samsohn0128** [comment]
백준에서 같은 문제 찾아서 제출해보니까 로직엔 문제가 없었는데, 정렬하는 부분에서 내 컴터에선 괜찮은데 제출 서버에서 IllegalArguments 런타임에러가 났네용
