### ISSUE TITLE
[230918] SW Expert Academy - 점심 식사시간

### ISSUE THREAD

**Issue by yoseph0310** [SSAFY-Coach/SamsungAlgorithm-SecondHalf-23#5]
### 문제 개요

- 사이트 : SW Expert Academy
- 번호 : 2383
- 제목 : [모의 SW 역량테스트] 점심 식사시간
- 링크 : https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5-BEE6AK0DFAVl&categoryId=AV5-BEE6AK0DFAVl&categoryType=CODE&problemTitle=2383&orderBy=FIRST_REG_DATETIME&selectCodeLang=ALL&select-1=&pageSize=10&pageIndex=1

**Comment by samsohn0128** [comment]
@yoseph0310 테케 계속 46개만 맞는데 시간되면 한번 봐주라 흑흑

**Comment by yoseph0310** [comment]
> @yoseph0310 테케 계속 46개만 맞는데 시간되면 한번 봐주라 흑흑

확인이요

**Comment by yoseph0310** [comment]
> @yoseph0310 테케 계속 46개만 맞는데 시간되면 한번 봐주라 흑흑

계단 1, 계단 2에 가까운 순으로 사람들을 배치하는 것이 아니라
완전 탐색으로 돌려야함.

문제 예시보면 계단 1에 거리가 더 가까움에도 계단 2로 가서 최소 값을 내는 것을 볼수있어용

**Comment by samsohn0128** [comment]
> > @yoseph0310 테케 계속 46개만 맞는데 시간되면 한번 봐주라 흑흑
> 
> 계단 1, 계단 2에 가까운 순으로 사람들을 배치하는 것이 아니라 완전 탐색으로 돌려야함.
> 
> 문제 예시보면 계단 1에 거리가 더 가까움에도 계단 2로 가서 최소 값을 내는 것을 볼수있어용

와 찢었다

**Comment by yoseph0310** [comment]
> > > @yoseph0310 테케 계속 46개만 맞는데 시간되면 한번 봐주라 흑흑
> > 
> > 
> > 계단 1, 계단 2에 가까운 순으로 사람들을 배치하는 것이 아니라 완전 탐색으로 돌려야함.
> > 문제 예시보면 계단 1에 거리가 더 가까움에도 계단 2로 가서 최소 값을 내는 것을 볼수있어용
> 
> 와 찢었다

나도 저거 풀때 어떻게든 최적 먼저 내버리고 계단 내려가게 하고싶었다가
도저히 짱구굴려도 할 수가 없길래 문제 저 예시보고 이건 슈뢰딩거 정도가 와야하는 구나 싶어서 바로 완탐돌림

**Comment by samsohn0128** [comment]
> > > > @yoseph0310 테케 계속 46개만 맞는데 시간되면 한번 봐주라 흑흑
> > > 
> > > 
> > > 계단 1, 계단 2에 가까운 순으로 사람들을 배치하는 것이 아니라 완전 탐색으로 돌려야함.
> > > 문제 예시보면 계단 1에 거리가 더 가까움에도 계단 2로 가서 최소 값을 내는 것을 볼수있어용
> > 
> > 
> > 와 찢었다
> 
> 나도 저거 풀때 어떻게든 최적 먼저 내버리고 계단 내려가게 하고싶었다가 도저히 짱구굴려도 할 수가 없길래 문제 저 예시보고 이건 슈뢰딩거 정도가 와야하는 구나 싶어서 바로 완탐돌림

풀었따리~

**Comment by hadevyi** [comment]
테스트 케이스 2개가 막혔는데 예외케이스를 못찾고 있습니다 ㅜㅜ
헤엄~!!!
