### ISSUE TITLE
[230919] CodeTree - 원자충돌

### ISSUE THREAD

**Issue by hadevyi** [SSAFY-Coach/SamsungAlgorithm-SecondHalf-23#6]
### 문제 개요

- 사이트 : CodeTree
- 제목 : 원자충돌
- 링크 : https://www.codetree.ai/training-field/frequent-problems/problems/atom-collision/description?page=1&pageSize=20&tier=1%2C12&statuses=Ready

**Comment by samsohn0128** [comment]
@yoseph0310 
나도 태케 10번 오답인데 어떻게 해결했나요?!
왤케 디버깅이 안대지

**Comment by yoseph0310** [comment]
@samsohn0128 아점먹고 카페가서 확인해볼게용 푼지좀 되서 왜안됐는지 기억이 안나네

**Comment by samsohn0128** [comment]
@yoseph0310 아니당 드디어 풀어따

**Comment by yoseph0310** [comment]
@samsohn0128 뭐가문제엿어유

**Comment by samsohn0128** [comment]
@yoseph0310 내가 격자 넘어갓을때 모드연산하는걸 이상하게하고잇엇네 ㅋㅋㅋ
